antons-auto.mvc/Controllers/AboutController.cs
using System.Linq;
using antons_auto.mvc.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace antons_auto.mvc.Controllers
{
    public class AboutController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AboutController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var imageUrls = _context.Cars
                .Include(x => x.CarModel)
                .Include(x => x.CarModel.CarBrand)
                .Where(s => !string.IsNullOrEmpty(s.ImageUrl))
                .Select(s => s.ImageUrl).ToList();
            
            return View(imageUrls);
        }
    }
}

antons-auto.mvc/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using antons_auto.mvc.Data;
using antons_auto.mvc.Data.Entities;
using antons_auto.mvc.ServiceProxies;
using antons_auto.mvc.Shared;
using antons_auto.mvc.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query;

namespace antons_auto.mvc.Controllers
{
    public class CarsController : Controller
    {
        private const int PAGE_SIZE = 6;
        private const string GOOGLE_MAPS_KEY = "AIzaSyArmzkH-4mqeXhynpdKa-1xRdjCTInXRzY";
        private static string _noImage;

        private readonly ApplicationDbContext _context;
        private readonly IDawaServiceProxy _dawaServiceProxy;

        private readonly List<SelectListItem> _sorting = new List<SelectListItem>
        {
            new SelectListItem {Value = "newest", Text = "Nyeste", Selected = false},
            new SelectListItem {Value = "carmodel", Text = "Bilmærke", Selected = false},
            new SelectListItem {Value = "price", Text = "Pris", Selected = false}
        };

        public CarsController(ApplicationDbContext context, IDawaServiceProxy dawaServiceProxy)
        {
            _context = context;
            _dawaServiceProxy = dawaServiceProxy;
        }

        public async Task<IActionResult> Index(
            string sortOrder = "newest",
            string searchString = "",
            int pageNumber = 1)
        {
            _noImage =
                $"{HttpContext.Request.Scheme}://{HttpContext.Request.Host.Value}/images/image_not_available.jpg";

            _sorting.ForEach(f => f.Selected = f.Value == sortOrder);


            var cars = _context.Cars
                .Include(x => x.CarModel)
                .Include(x => x.CarModel.CarBrand);

            var carsFiltered = CarsFiltered(searchString, cars);
            var carsSorted = SortCars(carsFiltered, sortOrder).AsNoTracking();
            var paginatedList = await PaginatedList<Car>.CreateAsync(carsSorted, pageNumber, PAGE_SIZE);
            var carsViewModel = paginatedList.Select(MapToViewModel);

            ViewData["sorting"] = _sorting;
            ViewData["sortOrderSelect"] = sortOrder;
            ViewData["currentFilter"] = searchString;
            ViewData["pages"] = (int)(Math.Ceiling((decimal)carsSorted.Count() / (decimal)PAGE_SIZE));
            ViewData["pageIndex"] = pageNumber;

            return View(carsViewModel);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();

            var car = await _context.Cars
                .Include(x => x.CarModel)
                .Include(x => x.CarModel.CarBrand)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.CarID == id);

            if (car == null) return NotFound();
            ViewData["google-maps-key"] = GOOGLE_MAPS_KEY;
            var carViewModel = MapToViewModel(car);

            return View(carViewModel);
        }

        public async Task<IActionResult> Create()
        {
            await ViewDataCarBrands();
            await ViewDataCarModels();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("CarId,CarBrandID,CarModelID,Year,Price,MileAge,Address,AddressNo,PostalCode,ImageUrl")]
            CarViewModel carViewModel)
        {
            if (ModelState.IsValid)
            {
                var locationModel = _dawaServiceProxy.GetLocation(carViewModel.Address, carViewModel.AddressNo,
                    carViewModel.PostalCode);
                carViewModel.City = locationModel.City;
                carViewModel.Longitude = locationModel.Longitude;
                carViewModel.Latitude = locationModel.Latitude;

                var car = MapToModel(carViewModel);
                _context.Add(car);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(carViewModel);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null) return NotFound();

            var car = await _context.Cars
                .Include(x => x.CarModel)
                .Include(x => x.CarModel.CarBrand)
                .FirstOrDefaultAsync(m => m.CarID == id);

            if (car == null) return NotFound();
            var carViewModel = MapToViewModel(car);
            carViewModel.ImageUrl = carViewModel.ImageUrl.Equals(_noImage) ? string.Empty : carViewModel.ImageUrl;

            return View(carViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("CarID,CarBrandID, CarModelID,Year,Price,MileAge,Address,AddressNo,PostalCode,ImageUrl")]
            CarViewModel carViewModel)
        {
            if (id != carViewModel.CarID) return NotFound();

            if (ModelState.IsValid)
            {
                var locationModel = _dawaServiceProxy.GetLocation(carViewModel.Address, carViewModel.AddressNo,
                    carViewModel.PostalCode);
                carViewModel.City = locationModel.City;
                carViewModel.Longitude = locationModel.Longitude;
                carViewModel.Latitude = locationModel.Latitude;

                var car = MapToModel(carViewModel);
                try
                {
                    _context.Update(car);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CarExists(car.CarID))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(Index));
            }

            return View(carViewModel);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();

            var car = await _context.Cars
                .Include(x => x.CarModel)
                .Include(x => x.CarModel.CarBrand)
                .FirstOrDefaultAsync(m => m.CarID == id);

            if (car == null) return NotFound();
            var carViewModel = MapToViewModel(car);

            return View(carViewModel);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var car = await _context.Cars.FindAsync(id);
            _context.Cars.Remove(car);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // Private methods
        private bool CarExists(int id)
        {
            return _context.Cars.Any(e => e.CarID == id);
        }

        private async Task ViewDataCarBrands()
        {
            ViewData["CarBrands"] = new SelectList(await _context.CarBrands
                .OrderBy(o => o.Name)
                .AsNoTracking()
                .ToListAsync(), "CarBrandID", "Name", "CarBrandID");
        }

        private async Task ViewDataCarModels()
        {
            ViewData["CarModels"] = new SelectList(await _context.CarModels
                .Select(s => new { Id = $"{s.CarBrandID}#{s.CarModelID}", s.Name })
                .AsNoTracking()
                .ToListAsync(), "Id", "Name");
        }

        private static IQueryable<Car> CarsFiltered(string searchString, IIncludableQueryable<Car, CarBrand> cars)
        {
            var carsFiltered = cars.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
                carsFiltered = cars.Where(s =>
                        s.CarModel.CarBrand.Name.Contains(searchString) ||
                        s.CarModel.Name.Contains(searchString));

            return carsFiltered;
        }

        private static IQueryable<Car> SortCars(IQueryable<Car> cars, string sortOrder)
        {
            return sortOrder switch
            {
                "newest" => cars.OrderBy(o => o.CreationDate),
                "price" => cars.OrderBy(o => o.Price),
                _ => cars.OrderBy(o => o.CarModel.CarBrand.Name)
            };
        }

        private static CarViewModel MapToViewModel(Car car)
        {
            return new CarViewModel
            {
                CarID = car.CarID,
                CarBrandID = car.CarModel.CarBrandID,
                CarModelID = car.CarModelID.ToString(),
                CarBrandName = car.CarModel.CarBrand.Name,
                CarModelName = car.CarModel.Name,
                Year = car.Year,
                Price = car.Price,
                MileAge = car.MileAge,
                Address = car.Address,
                AddressNo = car.AddressNo,
                PostalCode = car.PostalCode,
                City = car.City,
                FullAddress = $"{car.Address} {car.AddressNo}, {car.City}",
                Longitude = car.Longitude,
                Latitude = car.Latitude,
                ImageUrl = car.ImageUrl ?? _noImage
            };
        }


        private static Car MapToModel(CarViewModel carViewModel)
        {
            var carModelID = int.Parse(carViewModel.CarModelID.Contains("#")
                ? carViewModel.CarModelID.Split("#")[1]
                : carViewModel.CarModelID);


            return new Car
            {
                CarID = carViewModel.CarID,
                CarModelID = carModelID,
                Year = carViewModel.Year,
                Price = carViewModel.Price,
                MileAge = carViewModel.MileAge,
                Address = carViewModel.Address,
                AddressNo = carViewModel.AddressNo,
                PostalCode = carViewModel.PostalCode,
                City = carViewModel.City,

antons-auto.mvc/Views/Shared/_CarPartial.cshtml
@model antons_auto.mvc.ViewModels.CarViewModel

@{
    var showButtons = (bool)ViewData["ShowButtons"];
}

<style>
    .card {
        width: 300px;
    }

    dt {
        float: left;
        clear: left;
        width: 85px;
    }

    dd {
        margin-left: 0;
    }
</style>

<div class="card mx-2 my-3 mt-lg-0">
    <div class="card-header">
        <span>@Html.DisplayFor(modelItem => Model.CarBrandName) @Html.DisplayFor(modelItem => Model.CarModelName)</span>
    </div>
    <div class="card-body pb-0">
        <div class="text-center">
            <img src=@Html.Encode(Model.ImageUrl) asp-append-version="true" style="max-width: 100%;">
        </div>
        <dl class="mb-0">
            <dt>@Html.DisplayNameFor(model => model.CarBrandName)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.CarBrandName)</dd>
            <dt>@Html.DisplayNameFor(model => model.CarModelName)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.CarModelName)</dd>
            <dt>@Html.DisplayNameFor(model => model.Year)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.Year)</dd>
            <dt>@Html.DisplayNameFor(model => model.Price)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.Price)</dd>
            <dt>@Html.DisplayNameFor(model => model.MileAge)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.MileAge)</dd>
            <dt>@Html.DisplayNameFor(model => model.FullAddress)</dt>
            <dd>@Html.DisplayFor(modelItem => modelItem.FullAddress)</dd>
        </dl>
    </div>
    @if (showButtons)
    {
        <div class="card-footer d-flex justify-content-around">
            <a asp-action="Edit" asp-route-id="@Model.CarID" class="btn btn-sm btn-warning btn-sm">Rediger</a>
            <a asp-action="Details" asp-route-id="@Model.CarID" class="btn btn-sm btn-info btn-sm">Detaljer</a>
            <a asp-action="Delete" asp-route-id="@Model.CarID" class="btn btn-sm btn-danger btn-sm">Slet</a>
        </div>
    }
</div>

antons-auto.mvc/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="da">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Antons Auto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Anton's Auto</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Velkommen</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Biler</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CarBrands" asp-action="Index">Bilmærker</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CarModels" asp-action="Index">Bilmodeller</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="About" asp-action="Index">Om</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Lars
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", false)
</body>
</html>

antons-auto.mvc/Views/Shared/_MapsPartial.cshtml
@model antons_auto.mvc.ViewModels.CarViewModel



<style>
    #map {
        align-items: center;
        display: flex;
        justify-content: center;
        min-height: 50vh;
    }
</style>

<script>
    let map;

    document.addEventListener("DOMContentLoaded",
        () => {
            const s = document.createElement("script");
            document.head.appendChild(s);
            s.addEventListener("load",
                () => {
                    var pos = {
                        lat: @Model.Latitude.ToString().Replace(",", "."),
                        lng: @Model.Longitude.ToString().Replace(",", ".")
                    };

                    map = new window.google.maps.Map(document.getElementById("map"),
                        {
                            center: pos,
                            zoom: 16,
                            mapTypeId: window.google.maps.MapTypeId.ROADMAP
                        });

                    var marker = new window.google.maps.Marker({ position: pos, map: map });
                });

            s.src = `https://maps.googleapis.com/maps/api/js?key=@ViewData["google-maps-key"]`;
        });
</script>

<div id="map"></div>